// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function ConnectWS(arg1:string,arg2:Record<string, string>):Promise<void>;

export function DisconnectWS():Promise<void>;

export function ExecuteBinaryRequest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Record<string, string>):Promise<string>;

export function LoadSchemasFromDir(arg1:string):Promise<domain.LoadResult>;

export function SaveCollection(arg1:domain.Collection):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SendWS(arg1:string,arg2:string):Promise<void>;
