// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectWS(arg1, arg2) {
  return window['go']['main']['App']['ConnectWS'](arg1, arg2);
}

export function DisconnectWS() {
  return window['go']['main']['App']['DisconnectWS']();
}

export function ExecuteBinaryRequest(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ExecuteBinaryRequest'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function LoadSchemasFromDir(arg1) {
  return window['go']['main']['App']['LoadSchemasFromDir'](arg1);
}

export function SaveCollection(arg1) {
  return window['go']['main']['App']['SaveCollection'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SendWS(arg1, arg2) {
  return window['go']['main']['App']['SendWS'](arg1, arg2);
}
